version: '3.7'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - /home/samasri/bikeshare-db/db-files:/var/lib/mysql
    logging:
      driver: local
  mw:
    image: samasri/toronto-bikeshare-mw
    depends_on:
      - "db"
    ports:
      - '3000:3000'
    volumes:
      - ./bikeshare-mw:/usr/src/app
  fe:
    image: samasri/toronto-bikeshare-fe
    depends_on:
      - "db"
    ports:
      - '3001:3000'
    volumes:
      - ./bikeshare-fe:/usr/src/app